name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  DOXYGEN_VERSION: 1.12.0
  DOXYGEN_MD5SUM: fd96a5defa535dfe2e987b46540844a4

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up env
        run: |
          pip install -r requirements-actions.txt
          pip install -r doc/requirements.txt
          pip3 install  mlx-traceability strictdoc

      - name: Setup workspace
        run: |
          west init -l .
          west update

      - name: install-pkgs
        run: |
          sudo apt-get update
          sudo apt-get install -y wget python3-pip git ninja-build graphviz lcov
          wget --no-verbose "https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz"
          echo "${DOXYGEN_MD5SUM}  doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz" | md5sum -c
          if [ $? -ne 0 ]; then
          echo "Failed to verify doxygen tarball"
          exit 1
          fi
          sudo tar xf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz -C /opt
          echo "/opt/doxygen-${DOXYGEN_VERSION}/bin" >> $GITHUB_PATH
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Build Docs
        run: |
          pushd ../zephyr
          export ZEPHYR_BASE=${PWD}
          popd

          pushd ../doc/reqmgmt
          strictdoc export . --formats json
          popd
          pushd doc
          python ./scripts/requirements/create_req.py --json ../../doc/reqmgmt/output/json/index.json --output requirements.rst --format  rst
          python ./scripts/requirements/create_req.py --json ../../doc/reqmgmt/output/json/index.json --output requirements.dox --format  dox
          make html
          python scripts/list_all_tests.py --input _build/html/doxygen/xml/group__all__tests.xml --xml-dir _build/html/doxygen/xml --output-dir tests
          make html
          popd

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/_build/html

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
